version: '3.8'

services:
  api:
    build: .            
    container_name: housing_predictor
    ports:
      - "8000:8000"       
    volumes:
      - ./models:/app/models  
    environment:
      - PYTHONUNBUFFERED=1 